---
- name: User and Package Configuration
  hosts: all
  become: yes
  tasks:
    - name: Create skeleton directory for new users
      file:
        path: /etc/skel
        state: directory

    - name: Create nice-script.sh locally
      copy:
        content: |
          #!/bin/bash
          df -h
        dest: nice-script.sh
        mode: 0755

    - name: Copy nice-script.sh to skeleton directory
      copy:
        src: nice-script.sh
        dest: /etc/skel/nice-script.sh
        mode: 0755

    - name: Create /better-place directory if needed
      file:
        path: /better-place
        state: directory

    - name: Create user 'john' with home directory
      user:
        name: john
        comment: John Doe
        home: /better-place/john
        createhome: yes
        uid: 1234


    - name: Allow user 'john' to run whoami with sudo
      lineinfile:
        path: /etc/sudoers
        line: 'john ALL=(ALL) NOPASSWD: /usr/bin/whoami'
        validate: 'visudo -cf %s'
        create: yes

    - name: Install packages
      apt:
        name:
          - tmux
          - vim
        state: present
