
name: Deploy Images to Github Container Registry

env:
  DOTNET_VERSION: '6.0.x'

on:
#   schedule:
#    - cron: '0 19 * * 6' 
  workflow_run:
    workflows: ["Periodic CI"]
    branches:
      - main
 
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GIT_TOKEN}}

          - name: 'Build Image and Push to registry'
            run: |
              docker build . --tag ghcr.io/elsie-dev/flaskuser:latest
              docker push ghcr.io/elsie-dev/flaskuser:latest
